#!/bin/sh

#Shell Backup Script


#Environment
distro=$(cut -d"=" -f2 /etc/*-release | sed -n '1p')
data=$(/bin/date +%d-%m-%y)
backup_webserver=~/backup-web-server
apache2_files=/etc/apache2
apache2_log=/var/log/apache2
httpd_files=/etc/httpd
httpd_log=/var/log/httpd
www_files=/etc/www
www_log=/var/www

#Backup Files
mkdir $backup_webserver
#Creating Backup
if [ "$distro" = Ubuntu ]; then
  tar -zcf backup-apache2-${data}.tar.gz $apache2_files && mv backup-apache2-${data}.tar.gz $backup_webserver
  tar -zcf backup-wwww-${data}.tar.gz $www_files && mv backup-wwww-${data}.tar.gz $backup_webserver
  tar -zcf backup-log-${data}.tar.gz $apache2_log && mv backup-log-${data}.tar.gz $backup_webserver
else
  tar -zcf backup-httpd-${data}.tar.gz $httpd_files && mv backup-httpd-${data}.tar.gz $backup_webserver
  tar -zcf backup-wwww-${data}.tar.gz $www_files && mv backup-wwww-${data}.tar.gz $backup_webserver
  tar -zcf backup-log-${data}.tar.gz $httpd_log && mv backup-log-${data}.tar.gz $backup_webserver
fi


#Verify Backup
if [ "$?" = 1 ]; then
  echo "Successful" >> /var/log/script-backup.log
else
  echo "Unsuccessful" >> /var/log/script-backup.log
fi


var=$(dialog --backtitle Backup_Webserver --title backup_webserver --stdout --menu Choose an option: ' 0 0 0 1 'BACKUP' 2 'RESTORE')

case $var in
1) dialog --backtitle backup_webserver --title BACKUP --inputbox home/user/Desktop/ 0 0;;
2) dialog --backtitle backup_webserver --title RESTORE --inputbox home/user/Desktop/bkp_web 0 0;;
esac

#if [ $var = 1 ]; then
# dialog --backtitle Backup_Webserver --title BACKUP --inputbox home/user/Desktop/ 0 0
#else [ $var = 2 ] then
# dialog --backtitle Backup_Webserver --title RESTORE --inputbox home/user/Desktop/bkp_web 0 0
#fi
